ktor:
  deployment:
    port: 8080
  application:
    modules:
      - me.basehub.ApplicationKt.module

database:
  url: ${DATABASE_URL}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  driver: "org.postgresql.Driver"
